spring:
  application:
    name: sprint4-my-blog-app

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema: classpath:postgresql_schema.sql

post:
  shorttext:
    size: 128

---

spring:
  config:
    activate:
      on-profile: isolation

  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:h2_schema.sql